# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f9745632fd75b1ff21094a6f2251b3957f134fc8fecb5a6ea1dec585b79c7547904ea2951015a251f8adaf019deb1d85e4183e40ad1adc6dadcedf8060911f3

test:
  secret_key_base: b38afd506b48db1b6e3c5b6228089211d6ac290c2d99286eb41d3db75bab48633e4d41ee5457b0ff411ec224abf50dafffdef4d0599a2612c27cff97506efa6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
